// ========== MOVIE DATA ==========
// 所有片单数据，按分类组织
const MOVIES = {
  'body-horror': [
    // === 1980-2000 ===
    { year: 1980, title_cn: '惊变', title_en: 'Altered States', country: '美国', desc: '科学家用致幻剂探索意识，身体发生退化变异', douban: 'https://movie.douban.com/subject/1293762/' },
    { year: 1981, title_cn: '美国狼人在伦敦', title_en: 'An American Werewolf in London', country: '美国/英国', desc: '美国青年在英国被狼人咬伤后逐渐变身', douban: 'https://movie.douban.com/subject/1295077/' },
    { year: 1982, title_cn: '怪形', title_en: 'The Thing', country: '美国', desc: '南极科考队遭遇能模仿任何生物的外星怪物', douban: 'https://movie.douban.com/subject/1296794/' },
    { year: 1983, title_cn: '录影带谋杀案', title_en: 'Videodrome', country: '加拿大', desc: '电视台经理沉迷神秘节目，身体产生诡异变异', douban: 'https://movie.douban.com/subject/1295276/' },
    { year: 1984, title_cn: '毒魔复仇', title_en: 'The Toxic Avenger', country: '美国', desc: '清洁工掉进毒液桶变身超级英雄惩恶扬善', douban: 'https://movie.douban.com/subject/1299475/' },
    { year: 1985, title_cn: '活跳尸', title_en: 'Re-Animator', country: '美国', desc: '疯狂医学生发明复活药剂，死人暴走失控', douban: 'https://movie.douban.com/subject/1305793/' },
    { year: 1986, title_cn: '变蝇人', title_en: 'The Fly', country: '美国/英国', desc: '科学家传送实验出错，基因与苍蝇融合逐渐异变', douban: 'https://movie.douban.com/subject/1293073/' },
    { year: 1987, title_cn: '猛鬼追魂', title_en: 'Hellraiser', country: '英国', desc: '魔方盒打开地狱之门，欲望与痛苦交织', douban: 'https://movie.douban.com/subject/2042941/' },
    { year: 1988, title_cn: '变形怪体', title_en: 'The Blob', country: '美国', desc: '外太空黏液怪物入侵小镇吞噬一切', douban: 'https://movie.douban.com/subject/1440617/' },
    { year: 1989, title_cn: '上流社会', title_en: 'Society', country: '美国', desc: '少年发现上流社会家族的恐怖变形秘密', douban: 'https://movie.douban.com/subject/2265805/' },
    { year: 1990, title_cn: '科学怪妓', title_en: 'Frankenhooker', country: '美国', desc: '男子用妓女身体部件拼接复活未婚妻', douban: 'https://movie.douban.com/subject/1958342/' },
    { year: 1991, title_cn: '死而复生', title_en: 'The Resurrected', country: '美国', desc: '化学家痴迷复活实验，妻子揭开恐怖真相', douban: 'https://movie.douban.com/subject/2138008/' },
    { year: 1992, title_cn: '群尸玩过界', title_en: 'Braindead', country: '新西兰', desc: '鼠猴咬人引发丧尸潮，电锯血浆大战', douban: 'https://movie.douban.com/subject/1300377/' },
    { year: 1993, title_cn: '融尸荡魂', title_en: 'Body Melt', country: '澳大利亚', desc: '药物实验导致居民身体恐怖融化变异', douban: '' },
    { year: 1994, title_cn: '玛丽雪莱的科学怪人', title_en: "Mary Shelley's Frankenstein", country: '美国/日本/英国', desc: '科学家用尸体拼造新生命，怪物复仇悲剧', douban: 'https://movie.douban.com/subject/1293778/' },
    { year: 1995, title_cn: '异种', title_en: 'Species', country: '美国', desc: '外星DNA培育的美女生物疯狂寻找配偶繁殖', douban: 'https://movie.douban.com/subject/1293442/' },
    { year: 1996, title_cn: '瘦到死', title_en: 'Thinner', country: '美国', desc: '肥胖律师被吉普赛人诅咒不断消瘦至死', douban: 'https://movie.douban.com/subject/1293390/' },
    { year: 1997, title_cn: '黑洞表面', title_en: 'Event Horizon', country: '英国/美国', desc: '失踪飞船重现，船员陷入地狱般的幻觉', douban: 'https://movie.douban.com/subject/1298041/' },
    { year: 1998, title_cn: '我的老师不是人', title_en: 'The Faculty', country: '美国', desc: '高中生发现老师被外星寄生虫控制', douban: 'https://movie.douban.com/subject/1294732/' },
    { year: 1999, title_cn: '切肤之爱', title_en: 'Audition', country: '日本', desc: '中年丧偶男选妻遇上温柔变态少女', douban: 'https://movie.douban.com/subject/37219321/' },
    { year: 2000, title_cn: '漩涡', title_en: 'Uzumaki', country: '日本', desc: '小镇被螺旋诅咒笼罩，居民身体扭曲变形', douban: 'https://movie.douban.com/subject/1308017/' },
    // === 2001-2025 ===
    { year: 2001, title_cn: '异魔禁区', title_en: 'Dagon', country: '西班牙', desc: '情侣漂流至诡异渔村，村民已变成鱼人', douban: 'https://movie.douban.com/subject/1695241/' },
    { year: 2002, title_cn: '切肤', title_en: 'In My Skin', country: '法国', desc: '女白领意外受伤后沉迷自我伤害无法自拔', douban: 'https://movie.douban.com/subject/1436885/' },
    { year: 2003, title_cn: '牛头', title_en: 'Gozu', country: '日本', desc: '黑帮小弟寻找消失的大哥，坠入超现实噩梦', douban: 'https://movie.douban.com/subject/1307866/' },
    { year: 2004, title_cn: '机械师', title_en: 'The Machinist', country: '西班牙/美国', desc: '失眠一年的工人身体极度消瘦，精神崩溃', douban: 'https://movie.douban.com/subject/1309160/' },
    { year: 2005, title_cn: '恐怖蜡像馆', title_en: 'House of Wax', country: '美国/澳大利亚', desc: '年轻人误入小镇蜡像馆，蜡像竟是真人制成', douban: 'https://movie.douban.com/subject/1309184/' },
    { year: 2006, title_cn: '撕裂人', title_en: 'Slither', country: '加拿大/美国', desc: '外星寄生虫入侵小镇，居民变异为恶心怪物', douban: 'https://movie.douban.com/subject/1465415/' },
    { year: 2007, title_cn: '恐怖爆发', title_en: 'Exte: Hair Extensions', country: '日本', desc: '死尸头发疯长被制成假发，佩戴者离奇惨死', douban: 'https://movie.douban.com/subject/1939690/' },
    { year: 2008, title_cn: '恐怖废墟', title_en: 'The Ruins', country: '美国/德国/澳大利亚', desc: '年轻人探索玛雅遗迹被食人藤蔓寄生', douban: 'https://movie.douban.com/subject/2132486/' },
    { year: 2009, title_cn: '人体蜈蚣', title_en: 'The Human Centipede', country: '荷兰/英国', desc: '变态医生将三人缝合成首尾相连的人体蜈蚣', douban: 'https://movie.douban.com/subject/4058698/' },
    { year: 2010, title_cn: '战斗少女', title_en: 'Mutant Girls Squad', country: '日本', desc: '少女16岁觉醒变异能力，手臂化为利刃', douban: 'https://movie.douban.com/subject/4290700/' },
    { year: 2011, title_cn: '吾栖之肤', title_en: 'The Skin I Live In', country: '西班牙', desc: '整形医生囚禁女子进行疯狂换肤实验', douban: 'https://movie.douban.com/subject/2997052/' },
    { year: 2012, title_cn: '病毒抗体', title_en: 'Antiviral', country: '加拿大/美国', desc: '未来世界贩卖明星病毒，员工私注感染濒死', douban: 'https://movie.douban.com/subject/6958992/' },
    { year: 2013, title_cn: '皮囊之下', title_en: 'Under the Skin', country: '英国/美国/瑞士', desc: '外星女子披人皮在苏格兰诱杀男性', douban: 'https://movie.douban.com/subject/3749974/' },
    { year: 2014, title_cn: '人形海象', title_en: 'Tusk', country: '美国', desc: '播客主持人被疯老头改造成人形海象', douban: 'https://movie.douban.com/subject/25770733/' },
    { year: 2015, title_cn: '变蚊人', title_en: 'Bite', country: '加拿大', desc: '女子被虫咬后逐渐变异为产卵的昆虫怪物', douban: 'https://movie.douban.com/subject/26474493/' },
    { year: 2016, title_cn: '虚空', title_en: 'The Void', country: '加拿大', desc: '医院被神秘教徒包围，内部现克苏鲁怪物', douban: 'https://movie.douban.com/subject/26427810/' },
    { year: 2017, title_cn: '生吃', title_en: 'Raw', country: '法国/比利时', desc: '素食少女进兽医学院后嗜血成瘾渴望生肉', douban: 'https://movie.douban.com/subject/26653833/' },
    { year: 2018, title_cn: '阴风阵阵', title_en: 'Suspiria', country: '意大利/美国', desc: '舞蹈学院暗藏女巫集会，身体被扭曲操控', douban: 'https://movie.douban.com/subject/3095514/' },
    { year: 2019, title_cn: '海滨别墅', title_en: 'The Beach House', country: '美国', desc: '情侣海边度假遭神秘微生物感染，身体溃烂', douban: 'https://movie.douban.com/subject/34809725/' },
    { year: 2020, title_cn: '占有者', title_en: 'Possessor', country: '加拿大/英国', desc: '女杀手通过脑植入控制他人身体执行暗杀', douban: 'https://movie.douban.com/subject/30220880/' },
    { year: 2021, title_cn: '钛', title_en: 'Titane', country: '法国/比利时', desc: '脑中植入钛板的少女与汽车交合后怀孕变异', douban: 'https://movie.douban.com/subject/34820925/' },
    { year: 2022, title_cn: '未来罪行', title_en: 'Crimes of the Future', country: '加拿大/法国/希腊/英国', desc: '未来人类随意改造身体，器官变异成为艺术', douban: 'https://movie.douban.com/subject/35448536/' },
    { year: 2023, title_cn: '寄人皮下', title_en: 'Suitable Flesh', country: '美国', desc: '心理医生被患者夺舍，灵魂在不同身体间跳跃', douban: 'https://movie.douban.com/subject/36155146/' },
    { year: 2024, title_cn: '某种物质', title_en: 'The Substance', country: '法国/英国/美国', desc: '过气女星注射回春药物，代价是身体恐怖崩坏', douban: 'https://movie.douban.com/subject/35882838/' },
    { year: 2025, title_cn: '丑陋的继姐', title_en: 'The Ugly Stepsister', country: '挪威/丹麦', desc: '灰姑娘黑暗改编，继姐为变美自残削骨', douban: 'https://movie.douban.com/subject/36471252/' },
  ],

  // 其他分类数据待补充
  'cthulhu': [],
  'rob-zombie': [],
  'tim-burton': [],
  'john-carpenter': [],
  'stephen-king': [],
  'del-toro': []
}
