// ========== MOVIE DATA ==========
// 所有片单数据，按分类组织
const MOVIES = {
  'body-horror': [
    // === 1980-2000 ===
    { year: 1980, title_cn: '惊变', title_en: 'Altered States', country: '美国', desc: '科学家用致幻剂探索意识，身体发生退化变异', douban: 'https://movie.douban.com/subject/1293762/' },
    { year: 1981, title_cn: '美国狼人在伦敦', title_en: 'An American Werewolf in London', country: '美国/英国', desc: '美国青年在英国被狼人咬伤后逐渐变身', douban: 'https://movie.douban.com/subject/1295077/' },
    { year: 1982, title_cn: '怪形', title_en: 'The Thing', country: '美国', desc: '南极科考队遭遇能模仿任何生物的外星怪物', douban: 'https://movie.douban.com/subject/1296794/' },
    { year: 1983, title_cn: '录影带谋杀案', title_en: 'Videodrome', country: '加拿大', desc: '电视台经理沉迷神秘节目，身体产生诡异变异', douban: 'https://movie.douban.com/subject/1295276/' },
    { year: 1984, title_cn: '毒魔复仇', title_en: 'The Toxic Avenger', country: '美国', desc: '清洁工掉进毒液桶变身超级英雄惩恶扬善', douban: 'https://movie.douban.com/subject/1299475/' },
    { year: 1985, title_cn: '活跳尸', title_en: 'Re-Animator', country: '美国', desc: '疯狂医学生发明复活药剂，死人暴走失控', douban: 'https://movie.douban.com/subject/1305793/' },
    { year: 1986, title_cn: '变蝇人', title_en: 'The Fly', country: '美国/英国', desc: '科学家传送实验出错，基因与苍蝇融合逐渐异变', douban: 'https://movie.douban.com/subject/1293073/' },
    { year: 1987, title_cn: '猛鬼追魂', title_en: 'Hellraiser', country: '英国', desc: '魔方盒打开地狱之门，欲望与痛苦交织', douban: 'https://movie.douban.com/subject/2042941/' },
    { year: 1988, title_cn: '变形怪体', title_en: 'The Blob', country: '美国', desc: '外太空黏液怪物入侵小镇吞噬一切', douban: 'https://movie.douban.com/subject/1440617/' },
    { year: 1989, title_cn: '上流社会', title_en: 'Society', country: '美国', desc: '少年发现上流社会家族的恐怖变形秘密', douban: 'https://movie.douban.com/subject/2265805/' },
    { year: 1990, title_cn: '科学怪妓', title_en: 'Frankenhooker', country: '美国', desc: '男子用妓女身体部件拼接复活未婚妻', douban: 'https://movie.douban.com/subject/1958342/' },
    { year: 1991, title_cn: '死而复生', title_en: 'The Resurrected', country: '美国', desc: '化学家痴迷复活实验，妻子揭开恐怖真相', douban: 'https://movie.douban.com/subject/2138008/' },
    { year: 1992, title_cn: '群尸玩过界', title_en: 'Braindead', country: '新西兰', desc: '鼠猴咬人引发丧尸潮，电锯血浆大战', douban: 'https://movie.douban.com/subject/1300377/' },
    { year: 1993, title_cn: '融尸荡魂', title_en: 'Body Melt', country: '澳大利亚', desc: '药物实验导致居民身体恐怖融化变异', douban: '' },
    { year: 1994, title_cn: '玛丽雪莱的科学怪人', title_en: "Mary Shelley's Frankenstein", country: '美国/日本/英国', desc: '科学家用尸体拼造新生命，怪物复仇悲剧', douban: 'https://movie.douban.com/subject/1293778/' },
    { year: 1995, title_cn: '异种', title_en: 'Species', country: '美国', desc: '外星DNA培育的美女生物疯狂寻找配偶繁殖', douban: 'https://movie.douban.com/subject/1293442/' },
    { year: 1996, title_cn: '瘦到死', title_en: 'Thinner', country: '美国', desc: '肥胖律师被吉普赛人诅咒不断消瘦至死', douban: 'https://movie.douban.com/subject/1293390/' },
    { year: 1997, title_cn: '黑洞表面', title_en: 'Event Horizon', country: '英国/美国', desc: '失踪飞船重现，船员陷入地狱般的幻觉', douban: 'https://movie.douban.com/subject/1298041/' },
    { year: 1998, title_cn: '我的老师不是人', title_en: 'The Faculty', country: '美国', desc: '高中生发现老师被外星寄生虫控制', douban: 'https://movie.douban.com/subject/1294732/' },
    { year: 1999, title_cn: '切肤之爱', title_en: 'Audition', country: '日本', desc: '中年丧偶男选妻遇上温柔变态少女', douban: 'https://movie.douban.com/subject/37219321/' },
    { year: 2000, title_cn: '漩涡', title_en: 'Uzumaki', country: '日本', desc: '小镇被螺旋诅咒笼罩，居民身体扭曲变形', douban: 'https://movie.douban.com/subject/1308017/' },
    // === 2001-2025 ===
    { year: 2001, title_cn: '异魔禁区', title_en: 'Dagon', country: '西班牙', desc: '情侣漂流至诡异渔村，村民已变成鱼人', douban: 'https://movie.douban.com/subject/1695241/' },
    { year: 2002, title_cn: '切肤', title_en: 'In My Skin', country: '法国', desc: '女白领意外受伤后沉迷自我伤害无法自拔', douban: 'https://movie.douban.com/subject/1436885/' },
    { year: 2003, title_cn: '牛头', title_en: 'Gozu', country: '日本', desc: '黑帮小弟寻找消失的大哥，坠入超现实噩梦', douban: 'https://movie.douban.com/subject/1307866/' },
    { year: 2004, title_cn: '机械师', title_en: 'The Machinist', country: '西班牙/美国', desc: '失眠一年的工人身体极度消瘦，精神崩溃', douban: 'https://movie.douban.com/subject/1309160/' },
    { year: 2005, title_cn: '恐怖蜡像馆', title_en: 'House of Wax', country: '美国/澳大利亚', desc: '年轻人误入小镇蜡像馆，蜡像竟是真人制成', douban: 'https://movie.douban.com/subject/1309184/' },
    { year: 2006, title_cn: '撕裂人', title_en: 'Slither', country: '加拿大/美国', desc: '外星寄生虫入侵小镇，居民变异为恶心怪物', douban: 'https://movie.douban.com/subject/1465415/' },
    { year: 2007, title_cn: '恐怖爆发', title_en: 'Exte: Hair Extensions', country: '日本', desc: '死尸头发疯长被制成假发，佩戴者离奇惨死', douban: 'https://movie.douban.com/subject/1939690/' },
    { year: 2008, title_cn: '恐怖废墟', title_en: 'The Ruins', country: '美国/德国/澳大利亚', desc: '年轻人探索玛雅遗迹被食人藤蔓寄生', douban: 'https://movie.douban.com/subject/2132486/' },
    { year: 2009, title_cn: '人体蜈蚣', title_en: 'The Human Centipede', country: '荷兰/英国', desc: '变态医生将三人缝合成首尾相连的人体蜈蚣', douban: 'https://movie.douban.com/subject/4058698/' },
    { year: 2010, title_cn: '战斗少女', title_en: 'Mutant Girls Squad', country: '日本', desc: '少女16岁觉醒变异能力，手臂化为利刃', douban: 'https://movie.douban.com/subject/4290700/' },
    { year: 2011, title_cn: '吾栖之肤', title_en: 'The Skin I Live In', country: '西班牙', desc: '整形医生囚禁女子进行疯狂换肤实验', douban: 'https://movie.douban.com/subject/2997052/' },
    { year: 2012, title_cn: '病毒抗体', title_en: 'Antiviral', country: '加拿大/美国', desc: '未来世界贩卖明星病毒，员工私注感染濒死', douban: 'https://movie.douban.com/subject/6958992/' },
    { year: 2013, title_cn: '皮囊之下', title_en: 'Under the Skin', country: '英国/美国/瑞士', desc: '外星女子披人皮在苏格兰诱杀男性', douban: 'https://movie.douban.com/subject/3749974/' },
    { year: 2014, title_cn: '人形海象', title_en: 'Tusk', country: '美国', desc: '播客主持人被疯老头改造成人形海象', douban: 'https://movie.douban.com/subject/25770733/' },
    { year: 2015, title_cn: '变蚊人', title_en: 'Bite', country: '加拿大', desc: '女子被虫咬后逐渐变异为产卵的昆虫怪物', douban: 'https://movie.douban.com/subject/26474493/' },
    { year: 2016, title_cn: '虚空', title_en: 'The Void', country: '加拿大', desc: '医院被神秘教徒包围，内部现克苏鲁怪物', douban: 'https://movie.douban.com/subject/26427810/' },
    { year: 2017, title_cn: '生吃', title_en: 'Raw', country: '法国/比利时', desc: '素食少女进兽医学院后嗜血成瘾渴望生肉', douban: 'https://movie.douban.com/subject/26653833/' },
    { year: 2018, title_cn: '阴风阵阵', title_en: 'Suspiria', country: '意大利/美国', desc: '舞蹈学院暗藏女巫集会，身体被扭曲操控', douban: 'https://movie.douban.com/subject/3095514/' },
    { year: 2019, title_cn: '海滨别墅', title_en: 'The Beach House', country: '美国', desc: '情侣海边度假遭神秘微生物感染，身体溃烂', douban: 'https://movie.douban.com/subject/34809725/' },
    { year: 2020, title_cn: '占有者', title_en: 'Possessor', country: '加拿大/英国', desc: '女杀手通过脑植入控制他人身体执行暗杀', douban: 'https://movie.douban.com/subject/30220880/' },
    { year: 2021, title_cn: '钛', title_en: 'Titane', country: '法国/比利时', desc: '脑中植入钛板的少女与汽车交合后怀孕变异', douban: 'https://movie.douban.com/subject/34820925/' },
    { year: 2022, title_cn: '未来罪行', title_en: 'Crimes of the Future', country: '加拿大/法国/希腊/英国', desc: '未来人类随意改造身体，器官变异成为艺术', douban: 'https://movie.douban.com/subject/35448536/' },
    { year: 2023, title_cn: '寄人皮下', title_en: 'Suitable Flesh', country: '美国', desc: '心理医生被患者夺舍，灵魂在不同身体间跳跃', douban: 'https://movie.douban.com/subject/36155146/' },
    { year: 2024, title_cn: '某种物质', title_en: 'The Substance', country: '法国/英国/美国', desc: '过气女星注射回春药物，代价是身体恐怖崩坏', douban: 'https://movie.douban.com/subject/35882838/' },
    { year: 2025, title_cn: '丑陋的继姐', title_en: 'The Ugly Stepsister', country: '挪威/丹麦', desc: '灰姑娘黑暗改编，继姐为变美自残削骨', douban: 'https://movie.douban.com/subject/36471252/' },
  ],

  'cthulhu': [
    { year: 1963, title_cn: '闹鬼的宫殿', title_en: 'The Haunted Palace', country: '美国', desc: '男子继承古堡后被祖先亡灵附身复仇', douban: 'https://movie.douban.com/subject/1305468/' },
    { year: 1965, title_cn: '殉魔记', title_en: 'Die, Monster, Die!', country: '英国/美国', desc: '陨石坠落庄园，辐射导致生物恐怖变异', douban: 'https://movie.douban.com/subject/2131857/' },
    { year: 1968, title_cn: '深红祭坛的诅咒', title_en: 'Curse of the Crimson Altar', country: '英国', desc: '男子寻找失踪兄弟，卷入古老巫术仪式', douban: '' },
    { year: 1970, title_cn: '敦威治恐怖事件', title_en: 'The Dunwich Horror', country: '美国', desc: '青年试图用魔法书召唤远古邪神降临人间', douban: 'https://movie.douban.com/subject/1780825/' },
    { year: 1981, title_cn: '鬼玩人', title_en: 'The Evil Dead', country: '美国', desc: '五人山间小屋度假，死灵之书唤醒远古恶魔', douban: 'https://movie.douban.com/subject/1300' },
    { year: 1985, title_cn: '活跳尸', title_en: 'Re-Animator', country: '美国', desc: '疯狂医学生发明复活药剂，死人暴走失控', douban: 'https://movie.douban.com/subject/1305793/' },
    { year: 1986, title_cn: '活魔人', title_en: 'From Beyond', country: '美国', desc: '科学家打开第六感官，引来异次元恐怖生物', douban: 'https://movie.douban.com/subject/1301878/' },
    { year: 1987, title_cn: '诅咒', title_en: 'The Curse', country: '美国', desc: '陨石坠落农场污染水源，全家人恐怖变异', douban: '' },
    { year: 1988, title_cn: '天妖', title_en: 'The Unnamable', country: '美国', desc: '大学生闯入闹鬼老宅，遭遇不可名状之物', douban: '' },
    { year: 1991, title_cn: '死而复生', title_en: 'The Resurrected', country: '美国', desc: '化学家痴迷复活实验，妻子揭开恐怖真相', douban: 'https://movie.douban.com/subject/2138008/' },
    { year: 1993, title_cn: '死灵之书', title_en: 'Necronomicon', country: '美国', desc: '洛夫克拉夫特偷读死灵之书，三段恐怖故事', douban: 'https://movie.douban.com/subject/1461003/' },
    { year: 1994, title_cn: '战栗黑洞', title_en: 'In the Mouth of Madness', country: '美国', desc: '调查员寻找失踪作家，现实与小说融为一体', douban: 'https://movie.douban.com/subject/1293765/' },
    { year: 1994, title_cn: '狂鬼吓人', title_en: 'Lurking Fear', country: '美国/罗马尼亚', desc: '小镇地下潜伏着嗜人怪物，幸存者绝望抵抗', douban: '' },
    { year: 1995, title_cn: '衰落的城堡', title_en: 'Castle Freak', country: '美国/意大利', desc: '美国家庭继承意大利古堡，地牢藏着畸形怪物', douban: 'https://movie.douban.com/subject/1461840/' },
    { year: 1997, title_cn: '黑洞表面', title_en: 'Event Horizon', country: '英国/美国', desc: '失踪飞船重现，船员陷入地狱般的幻觉', douban: 'https://movie.douban.com/subject/1298041/' },
    { year: 2001, title_cn: '异魔禁区', title_en: 'Dagon', country: '西班牙', desc: '情侣漂流至诡异渔村，村民已变成鱼人', douban: 'https://movie.douban.com/subject/1695241/' },
    { year: 2005, title_cn: '克苏鲁的召唤', title_en: 'The Call of Cthulhu', country: '美国', desc: '默片风格改编洛夫克拉夫特同名经典小说', douban: 'https://movie.douban.com/subject/1866805/' },
    { year: 2007, title_cn: '迷雾', title_en: 'The Mist', country: '美国', desc: '浓雾笼罩小镇，雾中藏着来自异次元的怪物', douban: 'https://movie.douban.com/subject/1945' },
    { year: 2010, title_cn: '瓦德玛尔阴宅2', title_en: 'The Valdemar Legacy II', country: '西班牙', desc: '阴宅深处隐藏通往异界的门，克苏鲁降临', douban: '' },
    { year: 2011, title_cn: '黑山羊', title_en: 'The Black Goat', country: '日本', desc: '少女在封闭村庄遭遇远古邪神崇拜仪式', douban: '' },
    { year: 2014, title_cn: '爱在初春惊变时', title_en: 'Spring', country: '美国', desc: '青年在意大利邂逅神秘女子，她有远古秘密', douban: 'https://movie.douban.com/subject/25900945/' },
    { year: 2015, title_cn: '魔女屋中之梦', title_en: 'Dreams in the Witch House', country: '美国', desc: '改编洛夫克拉夫特，学生租住女巫旧居噩梦连连', douban: '' },
    { year: 2016, title_cn: '虚空', title_en: 'The Void', country: '加拿大', desc: '医院被神秘教徒包围，内部现克苏鲁怪物', douban: 'https://movie.douban.com/subject/26427810/' },
    { year: 2018, title_cn: '湮灭', title_en: 'Annihilation', country: '美国/英国', desc: '女科学家深入神秘区域，基因被未知力量改写', douban: 'https://movie.douban.com/subject/21348914/' },
    { year: 2019, title_cn: '星之彩', title_en: 'Color Out of Space', country: '美国/葡萄牙/马来西亚', desc: '陨石坠落农场释放外星颜色，全家疯狂变异', douban: 'https://movie.douban.com/subject/30147027/' },
    { year: 2019, title_cn: '灯塔', title_en: 'The Lighthouse', country: '美国/加拿大', desc: '两个守塔人困在孤岛，在疯狂中坠入深渊', douban: 'https://movie.douban.com/subject/30143336/' },
    { year: 2020, title_cn: '深潜者', title_en: 'Underwater', country: '美国', desc: '深海钻井队遭遇远古巨型生物攻击', douban: 'https://movie.douban.com/subject/26348579/' },
    { year: 2020, title_cn: '躯壳', title_en: 'The Husk', country: '美国', desc: '人体被外星寄生体改造成新形态', douban: '' },
    { year: 2020, title_cn: '深海异兽', title_en: 'Sea Fever', country: '爱尔兰/瑞典/比利时', desc: '渔船被深海未知生物寄生，船员逐个感染', douban: 'https://movie.douban.com/subject/30394117/' },
    { year: 2023, title_cn: '寄人皮下', title_en: 'Suitable Flesh', country: '美国', desc: '心理医生被患者夺舍，灵魂在不同身体间跳跃', douban: 'https://movie.douban.com/subject/36155146/' },
  ],

  'rob-zombie': [
    { year: 2003, title_cn: '千尸屋', title_en: 'House of 1000 Corpses', country: '美国', desc: '四个年轻人误闯变态家族的恐怖屋', douban: 'https://movie.douban.com/subject/1306288/' },
    { year: 2005, title_cn: '千尸屋2', title_en: "The Devil's Rejects", country: '美国', desc: '变态家族被警方追捕，一路血腥逃亡', douban: 'https://movie.douban.com/subject/1418736/' },
    { year: 2007, title_cn: '万圣节', title_en: 'Halloween', country: '美国', desc: '迈克尔·迈尔斯的起源故事，重启经典', douban: 'https://movie.douban.com/subject/1793929/' },
    { year: 2009, title_cn: '万圣节2', title_en: 'Halloween II', country: '美国', desc: '迈克尔·迈尔斯再次归来，更加残暴', douban: 'https://movie.douban.com/subject/3217' },
    { year: 2012, title_cn: '赛勒姆领主', title_en: 'The Lords of Salem', country: '美国/加拿大/英国', desc: '电台DJ收到神秘唱片，唤醒赛勒姆女巫诅咒', douban: 'https://movie.douban.com/subject/4820752/' },
    { year: 2016, title_cn: '31', title_en: '31', country: '美国', desc: '万圣节前夜五人被迫参加12小时杀人游戏', douban: 'https://movie.douban.com/subject/25870048/' },
    { year: 2019, title_cn: '千尸屋3', title_en: '3 from Hell', country: '美国', desc: '变态家族越狱后继续疯狂杀戮之旅', douban: 'https://movie.douban.com/subject/27109131/' },
    { year: 2022, title_cn: '蒙斯特一家', title_en: 'The Munsters', country: '美国', desc: '经典怪物家庭喜剧重启，Rob Zombie执导', douban: 'https://movie.douban.com/subject/35215390/' },
  ],

  'tim-burton': [
    { year: 1985, title_cn: '荒唐小混蛋奇遇记', title_en: "Pee-wee's Big Adventure", country: '美国', desc: '怪咖男孩横跨美国寻找被偷的自行车', douban: 'https://movie.douban.com/subject/1297577/' },
    { year: 1988, title_cn: '甲壳虫汁', title_en: 'Beetlejuice', country: '美国', desc: '新死夫妇请来恶灵驱赶占据老屋的活人', douban: 'https://movie.douban.com/subject/1295' },
    { year: 1989, title_cn: '蝙蝠侠', title_en: 'Batman', country: '美国/英国', desc: '黑暗骑士对抗疯狂小丑，哥特风格开山之作', douban: 'https://movie.douban.com/subject/1292217/' },
    { year: 1990, title_cn: '剪刀手爱德华', title_en: 'Edward Scissorhands', country: '美国', desc: '双手是剪刀的人造人闯入郊区小镇的温情悲剧', douban: 'https://movie.douban.com/subject/1292370/' },
    { year: 1992, title_cn: '蝙蝠侠归来', title_en: 'Batman Returns', country: '美国/英国', desc: '蝙蝠侠对抗企鹅人和猫女，更加黑暗扭曲', douban: 'https://movie.douban.com/subject/1292218/' },
    { year: 1994, title_cn: '艾德·伍德', title_en: 'Ed Wood', country: '美国', desc: '史上最烂导演的传奇人生，致敬B级片精神', douban: 'https://movie.douban.com/subject/1295' },
    { year: 1996, title_cn: '火星人玩转地球', title_en: 'Mars Attacks!', country: '美国', desc: '火星人入侵地球，黑色幽默讽刺全明星阵容', douban: 'https://movie.douban.com/subject/1293182/' },
    { year: 1999, title_cn: '断头谷', title_en: 'Sleepy Hollow', country: '美国/德国', desc: '警探调查无头骑士连环斩首案，哥特恐怖经典', douban: 'https://movie.douban.com/subject/1292360/' },
    { year: 2001, title_cn: '决战猩球', title_en: 'Planet of the Apes', country: '美国', desc: '宇航员坠落猿族统治的星球，人类沦为奴隶', douban: 'https://movie.douban.com/subject/1293025/' },
    { year: 2003, title_cn: '大鱼', title_en: 'Big Fish', country: '美国', desc: '儿子试图分辨父亲传奇故事中的真实与虚构', douban: 'https://movie.douban.com/subject/1291545/' },
    { year: 2005, title_cn: '查理和巧克力工厂', title_en: 'Charlie and the Chocolate Factory', country: '美国/英国', desc: '穷男孩获金券参观古怪巧克力大王的奇幻工厂', douban: 'https://movie.douban.com/subject/1309' },
    { year: 2005, title_cn: '僵尸新娘', title_en: 'Corpse Bride', country: '美国/英国', desc: '男子误将戒指戴给地下僵尸新娘，阴阳两难', douban: 'https://movie.douban.com/subject/1308782/' },
    { year: 2007, title_cn: '理发师陶德', title_en: 'Sweeney Todd', country: '美国/英国', desc: '复仇理发师用剃刀割喉，搭档做成肉馅饼', douban: 'https://movie.douban.com/subject/1793' },
    { year: 2010, title_cn: '爱丽丝梦游仙境', title_en: 'Alice in Wonderland', country: '美国', desc: '爱丽丝重返仙境对抗红皇后，视觉奇幻盛宴', douban: 'https://movie.douban.com/subject/2567' },
    { year: 2012, title_cn: '黑暗阴影', title_en: 'Dark Shadows', country: '美国', desc: '200年前被诅咒的吸血鬼在70年代苏醒', douban: 'https://movie.douban.com/subject/3594' },
    { year: 2012, title_cn: '科学怪狗', title_en: 'Frankenweenie', country: '美国', desc: '男孩用科学实验复活爱犬，引发怪物连锁反应', douban: 'https://movie.douban.com/subject/3076' },
    { year: 2014, title_cn: '大眼睛', title_en: 'Big Eyes', country: '美国', desc: '画家丈夫冒名顶替妻子画作，真相终被揭露', douban: 'https://movie.douban.com/subject/25812' },
    { year: 2016, title_cn: '佩小姐的奇幻城堡', title_en: "Miss Peregrine's Home for Peculiar Children", country: '美国/英国/比利时', desc: '男孩发现祖父秘密，进入异能儿童的时间循环', douban: 'https://movie.douban.com/subject/25827' },
    { year: 2019, title_cn: '小飞象', title_en: 'Dumbo', country: '美国', desc: '大耳小象被马戏团利用，孩子们帮它获得自由', douban: 'https://movie.douban.com/subject/25814' },
    { year: 2024, title_cn: '甲壳虫汁2', title_en: 'Beetlejuice Beetlejuice', country: '美国', desc: '时隔36年恶灵再度归来，三代人的哥特喜剧', douban: 'https://movie.douban.com/subject/26611' },
  ],

  'john-carpenter': [
    { year: 1974, title_cn: '黑星球', title_en: 'Dark Star', country: '美国', desc: '四人太空船执行炸星任务，荒诞黑色喜剧', douban: 'https://movie.douban.com/subject/1296456/' },
    { year: 1976, title_cn: '血溅十三号警署', title_en: 'Assault on Precinct 13', country: '美国', desc: '废弃警局被帮派围攻，警匪联手殊死搏斗', douban: 'https://movie.douban.com/subject/1300073/' },
    { year: 1978, title_cn: '月光光心慌慌', title_en: 'Halloween', country: '美国', desc: '杀人狂迈克尔万圣夜越狱回乡，砍杀式恐怖鼻祖', douban: 'https://movie.douban.com/subject/1293' },
    { year: 1980, title_cn: '雾', title_en: 'The Fog', country: '美国', desc: '浓雾中亡灵水手回归小镇复仇', douban: 'https://movie.douban.com/subject/1296' },
    { year: 1981, title_cn: '纽约大逃亡', title_en: 'Escape from New York', country: '美国/英国', desc: '未来纽约沦为监狱，独眼佣兵深入救总统', douban: 'https://movie.douban.com/subject/1293' },
    { year: 1982, title_cn: '怪形', title_en: 'The Thing', country: '美国', desc: '南极科考队遭遇能模仿任何生物的外星怪物', douban: 'https://movie.douban.com/subject/1296794/' },
    { year: 1983, title_cn: '克里斯汀魅力', title_en: 'Christine', country: '美国', desc: '被附身的1958年普利茅斯汽车疯狂杀人', douban: 'https://movie.douban.com/subject/1300' },
    { year: 1984, title_cn: '外星恋', title_en: 'Starman', country: '美国', desc: '外星人化身已故丈夫形象，与妻子踏上旅途', douban: 'https://movie.douban.com/subject/1305' },
    { year: 1986, title_cn: '妖魔大闹唐人街', title_en: 'Big Trouble in Little China', country: '美国', desc: '卡车司机闯入旧金山地下，对抗千年妖魔', douban: 'https://movie.douban.com/subject/1293' },
    { year: 1987, title_cn: '天魔回魂', title_en: 'Prince of Darkness', country: '美国', desc: '教堂地下室发现撒旦之子，科学与信仰碰撞', douban: 'https://movie.douban.com/subject/1297' },
    { year: 1988, title_cn: '极度空间', title_en: 'They Live', country: '美国', desc: '流浪汉戴上墨镜看到外星人伪装统治人类', douban: 'https://movie.douban.com/subject/1299' },
    { year: 1992, title_cn: '透明人的故事', title_en: 'Memoirs of an Invisible Man', country: '美国', desc: '意外隐身的男人被CIA追捕，逃亡中寻找解药', douban: 'https://movie.douban.com/subject/1302' },
    { year: 1994, title_cn: '战栗黑洞', title_en: 'In the Mouth of Madness', country: '美国', desc: '调查员寻找失踪作家，现实与小说融为一体', douban: 'https://movie.douban.com/subject/1293765/' },
    { year: 1995, title_cn: '魔童村', title_en: 'Village of the Damned', country: '美国', desc: '小镇女性集体怀孕，生下拥有超能力的恐怖儿童', douban: 'https://movie.douban.com/subject/1301' },
    { year: 1996, title_cn: '洛杉矶大逃亡', title_en: 'Escape from L.A.', country: '美国', desc: '独眼蛇再入沦陷的洛杉矶执行任务', douban: 'https://movie.douban.com/subject/1296' },
    { year: 1998, title_cn: '吸血鬼', title_en: 'Vampires', country: '美国', desc: '猎人团队追杀远古吸血鬼大师，阻止黑暗仪式', douban: 'https://movie.douban.com/subject/1297' },
    { year: 2001, title_cn: '火星幽灵', title_en: 'Ghosts of Mars', country: '美国', desc: '火星殖民地被远古幽灵附身，变成嗜杀狂战士', douban: 'https://movie.douban.com/subject/1296' },
    { year: 2010, title_cn: '鬼病院', title_en: 'The Ward', country: '美国', desc: '精神病院女患者逐个神秘消失，真相令人崩溃', douban: 'https://movie.douban.com/subject/4006150/' },
  ],

  'stephen-king': [
    { year: 1976, title_cn: '魔女嘉莉', title_en: 'Carrie', country: '美国', desc: '被欺凌的少女在舞会上爆发念力血洗全场', douban: 'https://movie.douban.com/subject/1293493/' },
    { year: 1980, title_cn: '闪灵', title_en: 'The Shining', country: '美国/英国', desc: '作家带家人看管雪山酒店，逐渐被邪灵吞噬', douban: 'https://movie.douban.com/subject/1293' },
    { year: 1983, title_cn: '克里斯汀魅力', title_en: 'Christine', country: '美国', desc: '被附身的1958年汽车疯狂杀人', douban: 'https://movie.douban.com/subject/1300' },
    { year: 1984, title_cn: '玉米地的小孩', title_en: 'Children of the Corn', country: '美国', desc: '小镇儿童集体杀死成年人，在玉米地祭祀邪神', douban: 'https://movie.douban.com/subject/1297' },
    { year: 1986, title_cn: '伴我同行', title_en: 'Stand by Me', country: '美国', desc: '四个少年踏上寻找尸体的冒险之旅', douban: 'https://movie.douban.com/subject/1295' },
    { year: 1989, title_cn: '宠物坟场', title_en: 'Pet Sematary', country: '美国', desc: '印第安墓地能复活死者，但回来的不再是从前', douban: 'https://movie.douban.com/subject/1296' },
    { year: 1990, title_cn: '危情十日', title_en: 'Misery', country: '美国', desc: '作家被头号粉丝囚禁，强迫他写出满意的结局', douban: 'https://movie.douban.com/subject/1293' },
    { year: 1990, title_cn: '小丑回魂', title_en: 'It', country: '美国', desc: '小镇下水道藏着变形恶魔小丑，27年一轮回', douban: 'https://movie.douban.com/subject/1300' },
    { year: 1994, title_cn: '肖申克的救赎', title_en: 'The Shawshank Redemption', country: '美国', desc: '银行家含冤入狱，用智慧和耐心挖出自由之路', douban: 'https://movie.douban.com/subject/1292052/' },
    { year: 1995, title_cn: '热泪伤痕', title_en: 'Dolores Claiborne', country: '美国', desc: '女佣被控谋杀雇主，揭开尘封多年的家庭暗伤', douban: 'https://movie.douban.com/subject/1296' },
    { year: 1999, title_cn: '绿里奇迹', title_en: 'The Green Mile', country: '美国', desc: '死囚拥有神奇治愈力，善良灵魂面对残酷命运', douban: 'https://movie.douban.com/subject/1293' },
    { year: 2007, title_cn: '1408', title_en: '1408', country: '美国', desc: '作家入住闹鬼酒店房间，陷入层层噩梦', douban: 'https://movie.douban.com/subject/1793' },
    { year: 2007, title_cn: '迷雾', title_en: 'The Mist', country: '美国', desc: '浓雾笼罩小镇，雾中藏着来自异次元的怪物', douban: 'https://movie.douban.com/subject/1793' },
    { year: 2017, title_cn: '小丑回魂', title_en: 'It', country: '美国/加拿大', desc: '七个少年对抗下水道变形恶魔小丑', douban: 'https://movie.douban.com/subject/1793' },
    { year: 2019, title_cn: '睡梦医生', title_en: 'Doctor Sleep', country: '美国/英国', desc: '闪灵续集，丹尼长大后对抗吸取儿童灵能的邪教', douban: 'https://movie.douban.com/subject/2462' },
    { year: 2019, title_cn: '宠物坟场', title_en: 'Pet Sematary', country: '美国', desc: '重启版，死去的女儿从墓地归来不再是从前', douban: 'https://movie.douban.com/subject/2717' },
  ],

  'del-toro': [
    { year: 1993, title_cn: '魔鬼银爪', title_en: 'Cronos', country: '墨西哥', desc: '古董商发现永生装置，代价是变成嗜血怪物', douban: 'https://movie.douban.com/subject/1293' },
    { year: 1997, title_cn: '变种DNA', title_en: 'Mimic', country: '美国', desc: '基因改造昆虫进化成人形，潜伏在地铁隧道', douban: 'https://movie.douban.com/subject/1294' },
    { year: 2001, title_cn: '鬼童院', title_en: "The Devil's Backbone", country: '西班牙/墨西哥', desc: '内战时期孤儿院闹鬼，男孩揭开炸弹与亡灵秘密', douban: 'https://movie.douban.com/subject/1303' },
    { year: 2002, title_cn: '刀锋战士2', title_en: 'Blade II', country: '美国/德国', desc: '吸血鬼猎人联手吸血鬼对抗变异嗜血新种族', douban: 'https://movie.douban.com/subject/1293' },
    { year: 2004, title_cn: '地狱男爵', title_en: 'Hellboy', country: '美国', desc: '二战召唤的恶魔婴儿长大后为人类对抗超自然', douban: 'https://movie.douban.com/subject/1304' },
    { year: 2006, title_cn: '潘神的迷宫', title_en: "Pan's Labyrinth", country: '西班牙/墨西哥/美国', desc: '内战阴影下少女进入奇幻地下王国完成三个任务', douban: 'https://movie.douban.com/subject/1456' },
    { year: 2008, title_cn: '地狱男爵2：黄金军团', title_en: 'Hellboy II: The Golden Army', country: '美国/德国', desc: '精灵王子率黄金军团进攻人类世界', douban: 'https://movie.douban.com/subject/2035' },
    { year: 2013, title_cn: '环太平洋', title_en: 'Pacific Rim', country: '美国', desc: '巨型机甲战士对抗深海裂缝涌出的怪兽军团', douban: 'https://movie.douban.com/subject/3445' },
    { year: 2015, title_cn: '猩红山峰', title_en: 'Crimson Peak', country: '美国/加拿大', desc: '新娘嫁入阴森古宅，红色黏土下埋藏血腥秘密', douban: 'https://movie.douban.com/subject/3593' },
    { year: 2017, title_cn: '水形物语', title_en: 'The Shape of Water', country: '美国', desc: '哑女清洁工与被囚的两栖人坠入爱河', douban: 'https://movie.douban.com/subject/2623' },
    { year: 2021, title_cn: '玉面情魔', title_en: 'Nightmare Alley', country: '美国/墨西哥/加拿大', desc: '野心家在嘉年华学会读心术，一步步走向毁灭', douban: 'https://movie.douban.com/subject/2134' },
    { year: 2022, title_cn: '匹诺曹', title_en: 'Guillermo del Toro\'s Pinocchio', country: '美国/墨西哥', desc: '定格动画黑暗版匹诺曹，法西斯时代的生死寓言', douban: 'https://movie.douban.com/subject/2622' },
  ]
}
